"""MailMergeTemplate.apply_to_all_etc

Revision ID: 232ee7baa252
Revises: 650e128ad060
Create Date: 2025-08-06 10:39:23.521432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '232ee7baa252'
down_revision = '650e128ad060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_merge_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apply_to_all_agenda_items', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('apply_to_all_events', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('apply_to_all_courses', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_merge_template', schema=None) as batch_op:
        batch_op.drop_column('apply_to_all_agenda_items')
        batch_op.drop_column('apply_to_all_events')
        batch_op.drop_column('apply_to_all_courses')

    # ### end Alembic commands ###
