"""TemplateEvent.default_location_id

Revision ID: 650e128ad060
Revises: 8f10cb596fab
Create Date: 2025-06-27 15:21:24.762774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650e128ad060'
down_revision = '8f10cb596fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('template_event_default_location_location', 'location', ['default_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_event', schema=None) as batch_op:
        batch_op.drop_constraint('template_event_default_location_location', type_='foreignkey')
        batch_op.drop_column('default_location_id')

    # ### end Alembic commands ###
