"""TemplateEvent.sequence

Revision ID: 8f10cb596fab
Revises: 5c70464f99ae
Create Date: 2025-06-27 14:58:46.093496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f10cb596fab'
down_revision = '5c70464f99ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_event', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
