name: Deploy to Bare Metal

on:
  push:
    branches: [ preprod ]  # or 'master'

jobs:
  deploy:
    runs-on: debian-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PREPROD_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H 81.2.121.244 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh github@81.2.121.244 << 'EOF'
          cd /home/github/apps/outreachAdmin
          git pull origin preprod
          source venv/bin/activate
          pip install -r requirements.txt
          systemctl restart outreach.service
        EOF
