name: Deploy to Bare Metal

on:
  push:
    branches: [ preprod ]  # or 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: preprod
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PUBLIC_IPV4: ${{ secrets.PUBLIC_IPV4 }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H $PUBLIC_IPV4 >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      env:
          PUBLIC_IPV4: ${{ secrets.PUBLIC_IPV4 }}
          LOCAL_USERNAME: ${{ secrets.LOCAL_USERNAME }}
          ENV_NAME: ${{ vars.ENV_NAME }}
          SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
          SQLALCHEMY_DATABASE_URI: ${{ vars.SQLALCHEMY_DATABASE_URI }}
          O365_CLIENT_ID: ${{ vars.O365_CLIENT_ID }}
          O365_CLIENT_SECRET: ${{ secrets.O365_CLIENT_SECRET }}
          O365_TENANT_ID: ${{ vars.O365_TENANT_ID }}
      run: |
        ssh $LOCAL_USERNAME@$PUBLIC_IPV4 << 'EOF'
          export SECRET_KEY=$SECRET_KEY
          export SQLALCHEMY_DATABASE_URI=$SQLALCHEMY_DATABASE_URI
          export O365_CLIENT_ID=$O365_CLIENT_ID
          export O365_CLIENT_SECRET=$O365_CLIENT_SECRET
          export O365_TENANT_ID=$O365_TENANT_ID
          export FLASK_APP=app.py
          cd ~/apps/outreachAdmin
          git pull origin $ENV_NAME
          if [ ! -d "venv" ]; then python3 -m venv venv; fi
          source venv/bin/activate
          pip install -r requirements.txt
          echo $SQLALCHEMY_DATABASE_URI
          flask db upgrade
          sudo /bin/systemctl restart outreach.service
        EOF
